//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package pl.pwr.smartkill.tools;

import pl.pwr.smartkill.LocationService;
import pl.pwr.smartkill.activities.MapsActivity;


public final class LocationService_
    extends LocationService
{


    public LocationService_(MapsActivity map) {
		super(map);
		// TODO Auto-generated constructor stub
	}

	private void init_() {
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
