//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package pl.pwr.smartkill.tools;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import pl.pwr.smartkill.SKApplication;

public final class Misc_
    extends Misc
{

    private Context context_;

    private Misc_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
            app = ((SKApplication) activity.getApplication());
        }
    }

    public static Misc_ getInstance_(Context context) {
        return new Misc_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
