//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package pl.pwr.smartkill.tools;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class PreferencesHelper_
    extends SharedPreferencesHelper
{


    public PreferencesHelper_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public PreferencesHelper_.PreferencesHelperEditor_ edit() {
        return new PreferencesHelper_.PreferencesHelperEditor_(getSharedPreferences());
    }

    public StringPrefField lastLogin() {
        return stringField("lastLogin", "");
    }

    public StringPrefField lastPassword() {
        return stringField("lastPassword", "");
    }

    public final static class PreferencesHelperEditor_
        extends EditorHelper<PreferencesHelper_.PreferencesHelperEditor_>
    {


        PreferencesHelperEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<PreferencesHelper_.PreferencesHelperEditor_> lastLogin() {
            return stringField("lastLogin");
        }

        public StringPrefEditorField<PreferencesHelper_.PreferencesHelperEditor_> lastPassword() {
            return stringField("lastPassword");
        }

    }

}
